config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  resources :produtos, only: [:new, :create, :destroy, :edit, :update]

  get "produtos/busca" => "produtos#busca", as: :busca_produto

  root "produtos#index" # rota principal
end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
end

app/models/produto.rb
class Produto < ActiveRecord::Base

	belongs_to :departamento

	validates :quantidade, presence: true
	validates :nome, length: { minimum: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  def create
    @departamento = Departamento.new(departamento_params)

    if @departamento.save
      redirect_to @departamento, notice: 'Departamento was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /departamentos/1
  def update
    if @departamento.update(departamento_params)
      redirect_to @departamento, notice: 'Departamento was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /departamentos/1
  def destroy
    @departamento.destroy
    redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
	
	before_action :set_produto, only: [:edit, :update, :destroy]

	def index
		@produtos_por_nome  = Produto.order(:nome).limit(5)
		@produtos_por_preco  = Produto.order(:preco).limit(2) 
	end

	def new # mostrar pag para criar
    	@produto = Produto.new
    	renderiza_new
	end

	def create # criar um produto
	    @produto = Produto.new produto_params
	    if @produto.save
	        flash[:notice] = "Produto salvo com sucesso"
	        redirect_to root_url
	    else
	        renderiza_new
	    end
	end

	def destroy # deletar um produto
		@produto.destroy
		redirect_to root_url
	end

	def edit # mostrar pagina para atualizar
		renderiza_new
	end

	def update # atualizar produto
		valores = produto_params
		@produto.update(valores)
		if @produto.update(valores)
			flash[:notice] = "Produto atualizado com sucesso"
			redirect_to root_url
		else
			renderiza_new
		end
	end

	def busca # busca no header
		nome_a_buscar = "%#{params[:nome]}%"
    	@produtos = Produto.where "nome like ?", nome_a_buscar
	end

	private

	def renderiza_new
		@departamentos = Departamento.all
		render :new
	end

	def set_produto
		id = params[:id]
		@produto = Produto.find(id)
	end

	def produto_params
		params.require(:produto).permit :nome, :preco, :descricao, :quantidade, :departamento_id
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_for(@departamento) do |f| %>
  <% if @departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% @departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form' %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TshirtStore" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

  <%= nav_bar brand: "T-shirt Store", brand_link: root_url do %>
      <%= form_tag busca_produto_path, 
                    method: :get, 
                    class: "navbar-form navbar-right" do %>
          <div class="form-group">
              <%= text_field_tag :nome, nil, class: "form-control" %>
              <%= button_to "Buscar", nil, class: "btn btn-default" %>
          </div>
      <% end %>
  <% end %>

  <div class="container" >
	   <%= yield %>
  </div>
  
  </body>
</html>

app/views/produtos/_form.html.erb
<% @produto.errors.full_messages.each do |message| %>
	<div class="alert alert-danger" role="alert"><%= message %></div>
<% end %>

<%= form_for @produto do |f| %>
			
			<div class="form-group">
				<%= f.label :nome %> 
				<%= f.text_field :nome, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :departamento %> 
				<%= f.collection_select :departamento_id, @departamentos, :id, :nome, {}, class: "form-control"%>
			</div>

			<div class="form-group">
				<%= f.label :descricao %> 
				<%= f.text_area :descricao, class: "form-control", rows: 4 %>
			</div>

			<div class="form-inline">
				<div class="form-group">
					<%= f.label :quantidade %> 
					<%= f.number_field :quantidade, step: 1.0, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :preco %> 
					<%= f.number_field :preco, class: "form-control" %>
				</div>
			</div>

			<br/>
			<%= f.submit texto_da_acao, class: "btn btn-primary" %>
		<% end %>
</form>

app/views/produtos/_produto.html.erb
 <tr>
            <td><%= produto.nome %></%></td>
            <td><%= produto.descricao %></%></td>
            <td><%= produto.preco %></%></td>
            <td><%= produto.quantidade %></%></td>
            <td><%= produto.departamento %></%></td>
            <td><%= button_to "Remover", produto,
                                        method: :delete,
                                        class: "btn btn-danger",
                                        data: { confirm: "Tem certeza que deseja remover #{produto.nome}?" }  %></td>
            <td><%= link_to "Alterar", edit_produto_path(produto), class: "btn btn-default" %></td>
</tr>

app/views/produtos/busca.html.erb
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Quantidade</th> 
            <th>Departamento</th>       
            <th>Remover</th> 
            <th>Atualizar</th>        
        </tr>
    </thead>
    <tbody>
       <%= render partial: "produto" , collection: @produtos %>
    </tbody>
</table>

app/views/produtos/edit.html.erb
<%= render partial: 'form', locals: { texto_da_acao: 'Atualizar o produto'} %>

app/views/produtos/index.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success" role="alert">
		<%= flash[:notice] %>
	</div>
<% end %>

<table class="table table-bordered">	
			<thead>
				<tr>
					<th>Nome</th>
					<th>Descrição</th>
					<th>Preço</th>
					<th>Quantidade</th>
					<th>Departamento</th>
					<th>Remover</th>
					<th>Atualizar</th>    
				<tr>
			</thead>
			<tbody>
				<%= render partial: "produto", collection: @produtos_por_nome %>
			</tbody>
		</table>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Descrição</th>
					<th>Preço</th>
					<th>Quantidade</th>
					<th>Departamento</th>
					<th>Remover</th>
				<tr>
			</thead>
			<tbody>
				<%= render partial: "produto", collection: @produtos_por_preco  %>
			</tbody>
</table>

<%= link_to "Criar novo produto", new_produto_path %>

app/views/produtos/new.html.erb
<%= render partial: 'form', locals: { texto_da_acao: 'Criar o produto'} %>